# Challenge 8

Diagonally dominant function

## Function

In [1]:
import numpy as np

def diag_dominant(M):
    n = len(M)
    rows = []
    for i in range(n):
        rows.append(M[i,i] > sum(M[i]) - M[i,i])
    return all(rows)

## Testing

In [2]:
A = np.array([
    [10, 2, 1],
    [1, 12, 2],
    [2, 1, 15]])
B = np.array([
    [1, 3, 2],
    [4, 1, 5],
    [2, 6, 1]])
C = np.array([
    [9, 1, 0],
    [2, 8, 1],
    [1, 1, 7]])
D = np.array([
    [2, 5, 3],
    [6, 1, 4],
    [3, 7, 2]])

for M in [A,B,C,D]:
    print(M, f"\nIs the matrix diagonally dominant? {diag_dominant(M)}\n")

[[10  2  1]
 [ 1 12  2]
 [ 2  1 15]] 
Is the matrix diagonally dominant? True

[[1 3 2]
 [4 1 5]
 [2 6 1]] 
Is the matrix diagonally dominant? False

[[9 1 0]
 [2 8 1]
 [1 1 7]] 
Is the matrix diagonally dominant? True

[[2 5 3]
 [6 1 4]
 [3 7 2]] 
Is the matrix diagonally dominant? False

