# Challenge 5

LU Decomposition - Code up the algorithms for Gaussian Elimination and LU Decomposition from the Common Linear Algebra Common Algorithms slide deck.

## Setup

In [1]:
import numpy as np

## Gaussian Elimination

In [2]:
def gaussian_elimination(A, b):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    for i in range(n := len(b)):
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        # need true copies here to remove any old references
        tmp = np.array(A[i], dtype=float)
        A[i] = np.array(A[max_row], dtype=float)
        A[max_row] = np.array(tmp, dtype=float)
        # 1D arrays dont have this problem
        b[i], b[max_row] = b[max_row], b[i]
        
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] -= ratio * A[i]
            b[j] -= ratio * b[i]
    
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

## LU Decomposition

In [3]:
def lu_decomposition(A):
    L = np.eye(n := len(A))
    U = np.array(A, dtype=float)
    
    for i in range(n):
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    
    return L, U

## Testing

In [4]:
A = np.array([[2, 3, 1],
              [4, 7, -1],
              [-2, 2, 2]])
b = np.array([1, 3, 4])

x = gaussian_elimination(A, b)
L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("\nLower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)
print("\nConstant array b:\n", b)
print("Solution vector x:\n", x)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  2  2]]

Lower Triangular Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  5.  1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 18.]]

Constant array b:
 [1 3 4]
Solution vector x:
 [-1.0, 1.0, 0.0]
